### ISSUE TITLE
 FileNotFoundError: Couldn't find a metric script at /GLEM-main/src/utils/function/hf_f1.py

### ISSUE THREAD

**Issue by grassdeerdeer** [AndyJZhao/GLEM#14]
When I run command "python src/models/GLEM/trainGLEM.py", it will occur
```
FileNotFoundError: Couldn't find a metric script at /home/xxx/code/GLEM-main/src/utils/function/hf_f1.py
```
I didn't find hf_f1.py.

**Comment by wykk00** [comment]
The same issue with you. My solution is removing the others metrics, only keeping the accuracy one.

**Comment by lrlbbzl** [comment]
These files are originally from Huggingface. For example, I guess codes from https://huggingface.co/spaces/evaluate-metric/f1/blob/main/f1.py can be used as hf_f1.py.

**Comment by AndyJZhao** [comment]
Sorry for the late reply, I did not get the notification. Yes, I confirm the code is from https://huggingface.co/spaces/evaluate-metric/f1/blob/main/f1.py
