### ISSUE TITLE
Question about controlling alpha and beta in the experiment

### ISSUE THREAD

**Issue by liuximeng2** [AndyJZhao/GLEM#17]
Hi,

I have a question about how is the Figure 4 in the paper generated. I observed that in the util code for GNN and LM, alpha and beta are both represented as the variable pl_weight with default value of 0.5. Therefore, when testing on different alphas as shown in Fig 4, do we keep beta the same at its default value? Is it the same vice versa for testing different beta values?

Thank you so much!

**Comment by AndyJZhao** [comment]
Sorry for the late reply. I didn't receive the notifications for new issues. As far as I could remember, the alpha and beta was set to the best settings of each dataset.
