### ISSUE TITLE
For ogbn-arxiv dataset, how can I pretrain to generate "Deberta.emb"?

### ISSUE THREAD

**Issue by liwk19** [AndyJZhao/GLEM#3]
Thank you for your codes! I was trying to run GLEM+EnGCN on ogbn-arxiv. The readme in OGB/ogbn-arxiv says: "If you have the Deberta.emb pretrained from our framework in the GLEM/temp/prt_lm/arxiv_TA/Deberta/Ftv1/Deberta.emb, ...", but it doesn't say how to generate "Deberta.emb". Could you please tell me how to do it or provide a link to a related repository? Thank you!

**Comment by AndyJZhao** [comment]
Sorry for the late reply. The Deberta.emb is generated by finetuning as a text classification problem.
