### ISSUE TITLE
Reproduce GLEM+EnGCN results

### ISSUE THREAD

**Issue by r0mer0m** [AndyJZhao/GLEM#4]
`math` Import issue on EnGCN ([link](https://github.com/AndyJZhao/GLEM/blob/12da8c7f3a23baabd8bb2c80e524f3b9162e7f77/src/models/GNNs/EnGCN/model.py#L90)).

**Comment by AndyJZhao** [comment]
Sorry for the late reply. 
It seems like there is something wrong with the environment, you may want to set up a new Conda virtual environment, our environment is available [here](https://github.com/AndyJZhao/GLEM/blob/main/environment.yml).
