### ISSUE TITLE
Checkpoint for the models and node embeddings?

### ISSUE THREAD

**Issue by bigheiniu** [AndyJZhao/GLEM#8]
Hi Andy, 
I appreciate your work combining the language model and graph neural network. 
Do you guys plan to release the checkpoint for your model (LM + GNN) and the final node embedding from the language model and graph neural network?
This will help us a lot in reproducing your work.
Best,
Yichuan

**Comment by AndyJZhao** [comment]
Unfortunately, we did not archive these final embeddings. Due to limited bandwidth, it's hard for me to release them currently.
