### ISSUE TITLE
Error in eval_and_save() function in lm_trainer.py

### ISSUE THREAD

**Issue by JiaheDu** [AndyJZhao/GLEM#9]
There is something wrong in eval_and_save() function in lm_trainer.py. It is because of the return value
 mtc_dict = self.trainer.predict(self.datasets[split]).metrics
 in the inside function get_metric() gets no keys related to accuracy, but only about time and speed. Is it a problem with Python packages version?

Traceback (most recent call last):
  File "src/models/LMs/trainLM.py", line 17, in <module>
    trainer.eval_and_save()
  File "/...../GLEM-main/src/models/LMs/lm_trainer.py", line 170, in eval_and_save
    res = {'val_acc': res['valid_accuracy'], 'test_acc': res['test_accuracy']}
KeyError: 'valid_accuracy'

**Comment by haibo12** [comment]
How to resolve this issue?

**Comment by zyni2001** [comment]
How to resolve this issue?

**Comment by AndyJZhao** [comment]
https://github.com/AndyJZhao/GLEM/blob/fc2077a55460b46aa5719cd336d5ec71564e9cf7/src/models/LMs/lm_trainer.py#L160-L161

I think line 161 will construct the key "valid_accuracy" if the trainer has successfully predicted the results.
You might want to debug line 161 instead.
